---
-
  name: 'Install prerequisite firewalld, start and enable service'
  hosts: localhost
  become: yes 
  tasks:
    - package: 
        name: firewalld
        state: present
    - service:
        name: firewalld
        state: started
        enabled: true
# service firewalld status               